# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a65c4de0b92729fe9fcbf8c551dd2e1c96de6fcaa7fda65f2028ac891cb218283f0a0631164ab442c52d3c8a0bcf0fbd70d50dcefd998097ccfd0d370b8f2cea

test:
  secret_key_base: e20e4854c61743fe17de5b2d0145cbb659eeb758cfebaede6d48bcdf4426c49aab074fe8522e45b8c53a561205d1a7fa3907e9b9aa86955813915cf4bd33dca7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
